import Head from 'next/head'
import Layout from "../components/Global/Layout";
import HeroSection from '../components/Pages/Ecommerce/HeroSection';
import MobileSection from '../components/Pages/Ecommerce/MobileSection';
import PaymentPlatformsSections from '../components/Pages/Ecommerce/PaymentPlatformsSections';
import PlatformsSections from '../components/Pages/Ecommerce/PlatformsSections';
import ServicesSection from '../components/Pages/Ecommerce/ServicesSection';


import EcommerceSpanish from "../content/es/ecommerce.json";

export default function Home({ homeData }) {
  // const { locale } = useRouter();
  // const data = locale === "es" ? HomeSpanish : HomeEnglish;

  const data = EcommerceSpanish;
  return (
    <div>
    <Head>
        <title>Diseño y desarrollo de Ecommerce</title>
        <meta
            name="description"
            content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <Layout>
        <main className="relative overflow-x-clip">
           <HeroSection data={data.hero} />
           <ServicesSection data={data.services}/>
           <PaymentPlatformsSections data={data.payments}/>
           <MobileSection data={data.mobile_content} />
           <PlatformsSections data={data.platforms} />
        </main>
    </Layout>
</div>
  )
}


// export async function getStaticProps({locale}) {
//   const homeData = locale === "es" ? HomeSpanish : HomeEnglish;
//   return {
//     props: {
//       homeData
//     }, // will be passed to the page component as props
//   }
// }