import Head from 'next/head'
import Layout from "../components/Global/Layout";
import HeroSection from '../components/Pages/Ecommerce/HeroSection';
import PaymentPlatformsSections from '../components/Pages/Ecommerce/PaymentPlatformsSections';
import ServicesSection from '../components/Pages/Ecommerce/ServicesSection';


import EcommerceSpanish from "../content/es/ecommerce.json";

export default function Home({ homeData }) {
  // const { locale } = useRouter();

  // const data = locale === "es" ? HomeSpanish : HomeEnglish;

  const data = EcommerceSpanish;
  console.log(data)
  return (
    <div>
    <Head>
        <title>Agencia de diseño y desarrollo web</title>
        <meta
            name="description"
            content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <Layout>
        <main className="relative overflow-x-clip">
           <HeroSection data={data.hero} />
           <ServicesSection data={data.services}/>
           <PaymentPlatformsSections data={data.payments}/>
        </main>
    </Layout>
</div>
  )
}


// export async function getStaticProps({locale}) {
//   const homeData = locale === "es" ? HomeSpanish : HomeEnglish;
//   return {
//     props: {
//       homeData
//     }, // will be passed to the page component as props
//   }
// }